version: '3.6'
services:
  elasticsearch-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch-01
    restart: always
    environment:
      - node.name=elasticsearch-01
      - cluster.name=ctautocomplete-es
      - cluster.initial_master_nodes=elasticsearch-01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic

  ct-autocomplete:
    image: registry.ctcue.com/ctautocomplete:es7
    container_name: ct-autocomplete
    restart: always
    ports:
      - 4080:4080
    depends_on:
      - elasticsearch-01
    links:
      - elasticsearch-01
    volumes:
      - ./config/local_config.json:/app/config/local_config.json
      - ./data/concepts.txt:/app/scripts/output/concepts.txt
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
