version: '3.6'
services:
  elasticsearch-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch-01
    environment:
      - node.name=elasticsearch-01
      - cluster.name=ctautocomplete-es
      - cluster.initial_master_nodes=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic

  ct-autocomplete:
    image: registry.ctcue.com/ctautocomplete:es7
    container_name: ct-autocomplete
    ports:
      - 4080:4080
    volumes:
      - ./config/local_config.json:/app/config/local_config.json
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
